# Generated by Django 3.1.6 on 2021-02-23 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='\\+?1?\\d{9,15}$')]),
        ),
    ]
