# Generated by Django 3.1.6 on 2021-03-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rooms', models.PositiveIntegerField(default=0)),
                ('number_bathrooms', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=1)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='properties/photos')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.neighborhoods')),
            ],
        ),
    ]
