# Generated by Django 3.1.6 on 2021-03-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='id_neighborhood',
            new_name='neighborhood',
        ),
    ]
