# Generated by Django 3.1.6 on 2021-02-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='properties',
        ),
    ]
