# Generated by Django 3.1.6 on 2021-02-23 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_auto_20210223_0619'),
        ('properties', '0002_delete_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_rooms', models.PositiveIntegerField(default=0)),
                ('number_bathrooms', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=1)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='properties/photos')),
                ('id_neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.neighborhoods')),
            ],
        ),
    ]
