# Generated by Django 3.1.6 on 2021-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.IntegerField(choices=[(0, 'No Negotiation'), (1, 'Open Negotiation'), (2, 'Close Negotiation')], default=0)),
            ],
        ),
    ]
