# Generated by Django 3.1.6 on 2021-02-28 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_user', models.IntegerField(choices=[(0, 'No Negotiation'), (1, 'Open Negotiation'), (2, 'Close Negotiation')], default=0)),
            ],
        ),
    ]
