# Generated by Django 3.1.6 on 2021-02-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiation',
            old_name='id_user',
            new_name='id_profile',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='status',
            field=models.CharField(choices=[(0, 'No Negotiation'), (1, 'Open Negotiation'), (2, 'Close Negotiation')], default=0, max_length=50),
        ),
    ]
