# Generated by Django 3.1.6 on 2021-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_auto_20210224_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='status',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='type_user',
            field=models.IntegerField(choices=[(0, 'No Negotiation'), (1, 'Open Negotiation'), (2, 'Close Negotiation')], default=0),
        ),
    ]
